name: docs

on:
  push:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn

      - name: Build site
        run: yarn docs:build

      - name: Deploy to github pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}